version: '3.8'

services:
  flask_app:
    build: .
    restart: always
    container_name: laptop_plug
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ports:
      - "5009:5009"
    environment:
      - TUYA_ACCESS_ID=${TUYA_ACCESS_ID}
      - TUYA_ACCESS_KEY=${TUYA_ACCESS_KEY}
      - TUYA_BULB_ID=${TUYA_BULB_ID}
      - TUYA_LAPTOP_ID=${TUYA_LAPTOP_ID}
      - LAB_LOG_FILE_PATH=/logs/laptop_plug.log
