version: '3.8'

services:
  flask_app:
    build: .
    restart: always
    container_name: marks_container
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ports:
      - "5007:5007"
    volumes:
      - ${DOCKER_DATA}/marks_db:/app/marks_data
