## Iterating Over a DataFrame

Example 1 : Using iterrows() to extract data from DataFrame two wise

In [1]:
import pandas as pd 
diSales = {'yr1':{'Qtr1': 34500, 'Qtr2': 56000,'Qtr3': 47000,'Qtr4': 49000},
           'yr2':{'Qtr1': 44900,'Qtr2':51000,'Qtr3': 57000,'Qtr4': 59000},
           'yr3':{'Qtr1': 34500,'Qtr2': 34500,'Qtr3': 34500,'Qtr4': 34500}}
df1 = pd.DataFrame(diSales) 
print(df1)
for (row,rowSeries) in df1.iterrows():
    print("Row index:",row) 
    print("Containing") 
    print(rowSeries) 


        yr1    yr2    yr3
Qtr1  34500  44900  34500
Qtr2  56000  51000  34500
Qtr3  47000  57000  34500
Qtr4  49000  59000  34500
Row index: Qtr1
Containing
yr1    34500
yr2    44900
yr3    34500
Name: Qtr1, dtype: int64
Row index: Qtr2
Containing
yr1    56000
yr2    51000
yr3    34500
Name: Qtr2, dtype: int64
Row index: Qtr3
Containing
yr1    47000
yr2    57000
yr3    34500
Name: Qtr3, dtype: int64
Row index: Qtr4
Containing
yr1    49000
yr2    59000
yr3    34500
Name: Qtr4, dtype: int64


Example 2 : Using iterrows() to extract row-wise Series object

In [3]:
import pandas as pd 
diSales = {'yr1':{'Qtr1': 34500, 'Qtr2': 56000,'Qtr3': 47000,'Qtr4': 49000},
           'yr2':{'Qtr1': 44900,'Qtr2':51000,'Qtr3': 57000,'Qtr4': 59000},
           'yr3':{'Qtr1': 34500,'Qtr2': 34500,'Qtr3': 34500,'Qtr4': 34500}}
df1 = pd.DataFrame(diSales) 
print(df1) 
for(row,rowSeries) in df1.iterrows():
    print("Row index:",row) 
    print("Containing:") 
    i = 0 
    for val in rowSeries:
        print("At:",i, "position:",val) 
        i = i+1 

        yr1    yr2    yr3
Qtr1  34500  44900  34500
Qtr2  56000  51000  34500
Qtr3  47000  57000  34500
Qtr4  49000  59000  34500
Row index: Qtr1
Containing:
At: 0 position: 34500
At: 1 position: 44900
At: 2 position: 34500
Row index: Qtr2
Containing:
At: 0 position: 56000
At: 1 position: 51000
At: 2 position: 34500
Row index: Qtr3
Containing:
At: 0 position: 47000
At: 1 position: 57000
At: 2 position: 34500
Row index: Qtr4
Containing:
At: 0 position: 49000
At: 1 position: 59000
At: 2 position: 34500


Example 3 : Using iteritems() to extract dtat from dataframe column wise.

In [7]:
import pandas as pd 
diSales = {'yr1':{'Qtr1': 34500, 'Qtr2': 56000,'Qtr3': 47000,'Qtr4': 49000},
           'yr2':{'Qtr1': 44900,'Qtr2':51000,'Qtr3': 57000,'Qtr4': 59000},
           'yr3':{'Qtr1': 34500,'Qtr2': 34500,'Qtr3': 34500,'Qtr4': 34500}}
df1 = pd.DataFrame(diSales) 
print(df1) 
for(col,colSeries) in df1.items():
    print("Column index:", col)
    print("Containing") 
    print(colSeries) 


        yr1    yr2    yr3
Qtr1  34500  44900  34500
Qtr2  56000  51000  34500
Qtr3  47000  57000  34500
Qtr4  49000  59000  34500
Column index: yr1
Containing
Qtr1    34500
Qtr2    56000
Qtr3    47000
Qtr4    49000
Name: yr1, dtype: int64
Column index: yr2
Containing
Qtr1    44900
Qtr2    51000
Qtr3    57000
Qtr4    59000
Name: yr2, dtype: int64
Column index: yr3
Containing
Qtr1    34500
Qtr2    34500
Qtr3    34500
Qtr4    34500
Name: yr3, dtype: int64


Example 4 : Write a program to print the dataframe df one row at a time.

In [7]:
import pandas as pd 
dict = {'Name':["Ram","Pam","Sam"],'Marks':[70,95,80]} 
df = pd.DataFrame(dict, index = ['Rno1','Rno2','Rno3']) 
for i, j in df.iterrows():
    print(j) 
    print("_________________") 

Name     Ram
Marks     70
Name: Rno1, dtype: object
_________________
Name     Pam
Marks     95
Name: Rno2, dtype: object
_________________
Name     Sam
Marks     80
Name: Rno3, dtype: object
_________________


Example 5 : Write a program to print the DtaFrame df, one column at a time.

In [5]:
import pandas as pd 
dict = {'Name':["Ram","Pam","Sam"],'Marks':[70,95,80]} 
df = pd.DataFrame(dict, index = ['Rno1','Rno2','Rno3']) 
for i, j in df.items():
    print(j) 
    print("__________") 

Rno1    Ram
Rno2    Pam
Rno3    Sam
Name: Name, dtype: object
__________
Rno1    70
Rno2    95
Rno3    80
Name: Marks, dtype: int64
__________


Example 6: Write a program to print only the values from marks column, for each row.

In [6]:
import pandas as pd 
dict = {'Name':["Ram","Pam","Sam"],'Marks':[70,95,80]} 
df = pd.DataFrame(dict, index = ['Rno1','Rno2','Rno3']) 
for r, row in df.iterrows():
    print(row['Marks']) 
    print("______") 


70
______
95
______
80
______


## Binary Operations in a DataFrame

In [31]:
s = {'A':[1,2,3], 'B':[4,5,6],'C':[7,8,9]}
df1 = pd.DataFrame(s)
print(df1) 


   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [32]:
import numpy as np 
df2 = pd.DataFrame(np.array([[10,20,30],[40,50,60],[70,80,100]]),
                 columns=['A','B','C'])
print(df2) 

    A   B    C
0  10  20   30
1  40  50   60
2  70  80  100


In [33]:
df3 = pd.DataFrame(np.array([[100,200,300],[400,500,600]]),
                 columns=['A','B','Z'])
print(df3) 

     A    B    Z
0  100  200  300
1  400  500  600


In [34]:
df4 = pd.DataFrame(np.array([[ 1000,2000],[4000,5000],[7000,8000]]),
                 columns=['A','B'])
print(df4) 

      A     B
0  1000  2000
1  4000  5000
2  7000  8000


### Binary Addition

print(df1+df2) 

In [36]:
print(df1.add(df2))

    A   B    C
0  11  24   37
1  42  55   68
2  73  86  109


In [37]:
print(df1.radd(df2))

    A   B    C
0  11  24   37
1  42  55   68
2  73  86  109


### Binary Subtraction

In [42]:
print(df1-df2)

    A   B   C
0  -9 -16 -23
1 -38 -45 -52
2 -67 -74 -91


In [43]:
print(df1.sub(df2))

    A   B   C
0  -9 -16 -23
1 -38 -45 -52
2 -67 -74 -91


In [44]:
print(df1.rsub(df2))

    A   B   C
0   9  16  23
1  38  45  52
2  67  74  91


### Binary Multiplication

In [45]:
print(df1*df3)

       A       B   C   Z
0  100.0   800.0 NaN NaN
1  800.0  2500.0 NaN NaN
2    NaN     NaN NaN NaN


In [47]:
print(df1.mul(df4))

       A      B   C
0   1000   8000 NaN
1   8000  25000 NaN
2  21000  48000 NaN


In [48]:
print(df3.rmul(df2))

         A        B   C   Z
0   1000.0   4000.0 NaN NaN
1  16000.0  25000.0 NaN NaN
2      NaN      NaN NaN NaN


### Binary Division

In [49]:
print(df1/df2)

          A      B         C
0  0.100000  0.200  0.233333
1  0.050000  0.100  0.133333
2  0.042857  0.075  0.090000


In [50]:
print(df4.div(df2))

       A      B   C
0  100.0  100.0 NaN
1  100.0  100.0 NaN
2  100.0  100.0 NaN


In [51]:
print(df2.rdiv(df1))

          A      B         C
0  0.100000  0.200  0.233333
1  0.050000  0.100  0.133333
2  0.042857  0.075  0.090000


In [63]:
a = {'p1':[700,975,970,900],'p2':[490,460,570,590]} 
team1 = pd.DataFrame(a) 
print(team1) 

    p1   p2
0  700  490
1  975  460
2  970  570
3  900  590


In [64]:
a = {'p1':[1100,1275,1270,1400],'p2':[1400,1260,1500,1190]} 
team2 = pd.DataFrame(a) 
print(team2) 

     p1    p2
0  1100  1400
1  1275  1260
2  1270  1500
3  1400  1190


Example 7: Write a program to calculate total prices earned by both the teams in each round.

In [58]:
print("Team 1's performence") 
print(team1) 
print("Team 2's performence") 
print(team2) 
print("Points earned by the both teams:")  
print(team1.radd(team2)) 

Team 1's performence
    p1   p2
0  700  400
1  975  460
2  970  570
3  900  590
Team 2's performence
     p1    p2
0  1100  1400
1  1275  1200
2  1270  1500
3  1400  1190
Points earned by the both teams:
     p1    p2
0  1800  1800
1  2250  1660
2  2240  2070
3  2300  1780


Example 8 : Consider the points earned by two teams, display how much point difference Team2 has with Team1.

In [66]:
a = {'p1':[700,975,970,900],'p2':[490,460,570,590]} 
team1 = pd.DataFrame(a) 
print(team1) 
a = {'p1':[1100,1275,1270,1400],'p2':[1400,1260,1500,1190]} 
team2 = pd.DataFrame(a) 
print(team2) 
print("Team2's point difference:") 
print(team1.rsub(team2)) 

    p1   p2
0  700  490
1  975  460
2  970  570
3  900  590
     p1    p2
0  1100  1400
1  1275  1260
2  1270  1500
3  1400  1190
Team2's point difference:
    p1   p2
0  400  910
1  300  800
2  300  930
3  500  600


Example 9 : Given two dataframes storing points of a 2-player team in four rounds
, write a program to calculate average points obtained by each player in each round.

In [68]:
print("Team 1's performence") 
print(team1) 
print("Team 2's performence") 
print(team2) 
print("Average point scored by the each player:") 
av = (team1+team2)/2 
print(av) 

Team 1's performence
    p1   p2
0  700  490
1  975  460
2  970  570
3  900  590
Team 2's performence
     p1    p2
0  1100  1400
1  1275  1260
2  1270  1500
3  1400  1190
Average point scored by the each player:
       p1      p2
0   900.0   945.0
1  1125.0   860.0
2  1120.0  1035.0
3  1150.0   890.0


In [69]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2


## Functions min() and max()

In [72]:
# Syntax: 
#<df>.min(axis = None, skipna = None, numeric_only = None) 
#<df>.max(axis = None, skipna = None, numeric_only = None) 
print(g.min())                   
print(g.max())

Rice      814.6
Wheat       0.5
Pulses      1.7
Fruits     44.1
dtype: float64
Rice       13754.0
Wheat      30056.0
Pulses      2184.4
Fruits    140169.2
dtype: float64


In [73]:
print(g.min(axis = 1))

Andhra P.     931.0
Gujarat       818.0
Kerala          1.7
Punjab         33.0
Tripura         0.5
Uttar p.     2184.4
dtype: float64


In [74]:
print(g.max(axis = 1))

Andhra P.      7830.0
Gujarat       11950.0
Kerala         2404.8
Punjab        16440.5
Tripura         814.6
Uttar p.     140169.2
dtype: float64


In [76]:
print(g.min(skipna = True, numeric_only = True) )

Rice      814.6
Wheat       0.5
Pulses      1.7
Fruits     44.1
dtype: float64


In [77]:
print(g.max(skipna = True, numeric_only = True) )

Rice       13754.0
Wheat      30056.0
Pulses      2184.4
Fruits    140169.2
dtype: float64


In [86]:
import pandas as pd  
import numpy as np 
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,'NaN',99,95.0] 
e = [97,100.0,99,'NaN'] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)  

       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN


Example 10: Consider the dataframe dfmks given above. Write a program to print the maximum marks scored in each subject across all sections.

In [90]:
import pandas as pd  
import numpy as np 
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)  
print("Maximum marks scored in each subject:") 
print(s.max(axis = 1)) 


       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN
Maximum marks scored in each subject:
Acct     99.0
Eco      97.0
Eng      95.0
IP       99.0
Math    100.0
dtype: float64


Example 11: Consider the DataFrame(dfmks) given above program so that it considers only non-Nan values for calculation purpose.

In [94]:
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
#print(s)  
print("Maximum marks scored in each subject:") 
print(s.max(axis = 1, skipna = True)) 


Maximum marks scored in each subject:
Acct     99.0
Eco      97.0
Eng      95.0
IP       99.0
Math    100.0
dtype: float64


Example 12: Consider the marks 'DataFrame'(dfmks) given above. Write a program to print the maximum marks scored in a sections, across all subjects.

In [93]:
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
#print(s)  
print("Maximum marks scored in each subject:") 
print(s.max()) 


Maximum marks scored in each subject:
A     99.0
B    100.0
C     99.0
D     97.0
dtype: float64


## Functions mode(), mean(), median()

In [99]:
# *****Mode*****
#Syntax: <df>.mode(axis = 0, numeric_only = False) 
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,87,99,95.0] 
e = [97,100.0,99,99] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)  
print("Maximum marks scored in each subject:") 
print(s.max(axis = 1)) 
print(s) 


       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94   87.0  99  95.0
Math  97  100.0  99  99.0
Maximum marks scored in each subject:
Acct     99.0
Eco      97.0
Eng      95.0
IP       99.0
Math    100.0
dtype: float64
       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94   87.0  99  95.0
Math  97  100.0  99  99.0


Example 13: Consider the dataframe mks1 given above. Write a program to calculate mode(maximum repeated value) for each section.

import numpy as np 
print("Mode value for each section:") 
print(s.mode()) 

Example 14: Consider the dataframe mks1 given above. Write a program to calculate mode (maximum repeated value) for each subject.

In [116]:
a = [99,94,92,97] 
b = [90,94,92,97] 
c = [95,89,91,89] 
d = [94,87,99,95] 
e = [97,100,99,99] 
f = [a,b,c,d,e] 
k = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(k)  
print("Mode value for each subject:") 
print(k.mode(axis = 1 )) 
print(k.mode()) 


# in column A no no. has repeated that's why it has printed all the no. 
#in increasing order 
# In col. B 94 has repeated 2 times that's why it has printed only 94 
# in col. C 99 and 92 has repeated 2 times that's why it has printed both increasing 
# Similarly in next one 


       A    B   C   D
Acct  99   94  92  97
Eco   90   94  92  97
Eng   95   89  91  89
IP    94   87  99  95
Math  97  100  99  99
Mode value for each subject:
         0     1     2     3
Acct  92.0  94.0  97.0  99.0
Eco   90.0  92.0  94.0  97.0
Eng   89.0   NaN   NaN   NaN
IP    87.0  94.0  95.0  99.0
Math  99.0   NaN   NaN   NaN
    A     B     C     D
0  90  94.0  92.0  97.0
1  94   NaN  99.0   NaN
2  95   NaN   NaN   NaN
3  97   NaN   NaN   NaN
4  99   NaN   NaN   NaN


Example 15: Consider the dataframe mks1 given above.
Write a program to calculate median value for each section.

In [109]:
a = [99,94,92,97] 
b = [90,94,92,97] 
c = [95,89,91,89] 
d = [94,87,99,95] 
e = [97,100,99,99] 
f = [a,b,c,d,e] 
k = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(k)  
print("Median value for each section:") 
print(k.median()) 

       A    B   C   D
Acct  99   94  92  97
Eco   90   94  92  97
Eng   95   89  91  89
IP    94   87  99  95
Math  97  100  99  99
Median value for each section:
A    95.0
B    94.0
C    92.0
D    97.0
dtype: float64


Example 16: Consider the dataframe mks1 given above. Write a program to calculate median value for each subject. 

In [118]:
a = [99,94,92,97] 
b = [90,94,92,97] 
c = [95,89,91,89] 
d = [94,87,99,95] 
e = [97,100,99,99] 
f = [a,b,c,d,e] 
k = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(k)  
print("Median value for each subject:") 
print(k.median(axis = 1 ))

       A    B   C   D
Acct  99   94  92  97
Eco   90   94  92  97
Eng   95   89  91  89
IP    94   87  99  95
Math  97  100  99  99
Median value for each subject:
Acct    95.5
Eco     93.0
Eng     90.0
IP      94.5
Math    99.0
dtype: float64


Example 17: Consider the dataframe mks1 given above. Write a program to calculate average value(mean) for each section.

In [119]:
a = [99,94,92,97] 
b = [90,94,92,97] 
c = [95,89,91,89] 
d = [94,87,99,95] 
e = [97,100,99,99] 
f = [a,b,c,d,e] 
k = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(k) 
print("Mean value for each section:") 
print(k.mean()) 


       A    B   C   D
Acct  99   94  92  97
Eco   90   94  92  97
Eng   95   89  91  89
IP    94   87  99  95
Math  97  100  99  99
MEan value for each section:
A    95.0
B    92.8
C    94.6
D    95.4
dtype: float64


Example 18: Consider the dataframe mks1 given above. Write a program to calculate average value(mean) for each subject.

In [120]:
a = [99,94,92,97] 
b = [90,94,92,97] 
c = [95,89,91,89] 
d = [94,87,99,95] 
e = [97,100,99,99] 
f = [a,b,c,d,e] 
k = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(k)  
print("Mean value for each subject:") 
print(k.mean(axis = 1)) 


       A    B   C   D
Acct  99   94  92  97
Eco   90   94  92  97
Eng   95   89  91  89
IP    94   87  99  95
Math  97  100  99  99
Mean value for each subject:
Acct    95.50
Eco     93.25
Eng     91.00
IP      93.75
Math    98.75
dtype: float64


## Functions count() and sum()

Example 19: Consider the dataframe dfmks. Calculate how many exams were conducted, for each section.

In [124]:
# Syntax: <df>.count(axis = 0, numeric_only = False) 
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)  
print("No. of exams conducted by each section:") 
print(s.count()) 

       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN
No. of exams conducted by each section:
A    5
B    4
C    5
D    4
dtype: int64


Example 20: Consider the dataframe dfmks. Assuming that in  each section, only 1 student scored maximum marks in each subject, write a program to calculate the topper's total marks, in each section.

In [125]:
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s) 
print("Topper's total marks in each section:") 
print(s.sum())

       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN
Topper's total marks in each section:
A    475.0
B    377.0
C    473.0
D    378.0
dtype: float64


In [126]:
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)  
print(s.describe()) 

       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN
               A       B          C          D
count   5.000000    4.00   5.000000   4.000000
mean   95.000000   94.25  94.600000  94.500000
std     3.391165    4.50   4.037326   3.785939
min    90.000000   89.00  91.000000  89.000000
25%    94.000000   92.75  92.000000  93.500000
50%    95.000000   94.00  92.000000  96.000000
75%    97.000000   95.50  99.000000  97.000000
max    99.000000  100.00  99.000000  97.000000


## Functions quantile(), std() and var()

### quantile

In [128]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.quantile([0.25,0.5,0.75,1.0])) 
       

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
         Rice      Wheat   Pulses      Fruits
0.25   2048.7   2052.875    25.65    1872.825
0.50   4929.1   9588.750   425.50    7491.000
0.75  10553.0  19844.375   902.75   10920.000
1.00  13754.0  30056.000  2184.40  140169.200


In [129]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g)
print(g.quantile([0.25,0.5,0.75,1.0], axis = 1)) 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
      Andhra P.   Gujarat   Kerala     Punjab  Tripura  Uttar p.
0.25     4192.2   1652.00    57.40   5372.250   17.525   10861.6
0.50     7453.4   2333.50   113.10   9369.100   33.650   21905.0
0.75     7641.7   5040.25  1258.95  12799.775  236.725   57584.3
1.00     7830.0  11950.00  2404.80  16440.500  814.600  140169.2


Example 21: Given a dataframe mks2 storing marks of 10 students in a class, in five subject, as shown below. Write a program to measure the subject wise performence of the students, so that the teacher gets to know the following details (for each sunject): 

In [133]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88,90,41,61,42,68] 
b = [94,94,72,67,82,81,36,54,42,67] 
c = [95,89,71,69,82,79,51,60,45,66] 
d = [94,87,79,65,89,81,42,63,43,64] 
e = [97,100,65,69,86,84,40,55,40,60] 
df = [a,b,c,d,e] 
df1 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP','Math']) 
print(df1) 
print("Performance of students, subject wise") 
print(df1.quantile([0.25,0.5,0.75,1.0], axis = 1)) 


       0    1   2   3   4   5   6   7   8   9
Acct  99   94  81  70  88  90  41  61  42  68
Eco   94   94  72  67  82  81  36  54  42  67
Eng   95   89  71  69  82  79  51  60  45  66
IP    94   87  79  65  89  81  42  63  43  64
Math  97  100  65  69  86  84  40  55  40  60
Performance of students, subject wise
       Acct    Eco    Eng     IP    Math
0.25  62.75  57.25  61.50  63.25   56.25
0.50  75.50  69.50  70.00  72.00   67.00
0.75  89.50  81.75  81.25  85.50   85.50
1.00  99.00  94.00  95.00  94.00  100.00


### The std() Function

In [135]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.std())

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
Rice       5462.454504
Wheat     13846.150566
Pulses      854.872997
Fruits    55208.911975
dtype: float64


Example 22: Consider the mks2 DataFrame used in example 25 above. Write a program to calculate the standard deaviation for each subject.

In [136]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88,90,41,61,42,68] 
b = [94,94,72,67,82,81,36,54,42,67] 
c = [95,89,71,69,82,79,51,60,45,66] 
d = [94,87,79,65,89,81,42,63,43,64] 
e = [97,100,65,69,86,84,40,55,40,60] 
df = [a,b,c,d,e] 
df1 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP','Math']) 
print(df1) 
print("Standard deviation, subject wise") 
print(df1.std(axis = 1)) 


       0    1   2   3   4   5   6   7   8   9
Acct  99   94  81  70  88  90  41  61  42  68
Eco   94   94  72  67  82  81  36  54  42  67
Eng   95   89  71  69  82  79  51  60  45  66
IP    94   87  79  65  89  81  42  63  43  64
Math  97  100  65  69  86  84  40  55  40  60
Standard deviation, subject wise
Acct    20.699973
Eco     20.063510
Eng     16.021167
IP      18.397162
Math    21.680508
dtype: float64


### The var() Function

In [137]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88,90,41,61,42,68] 
b = [94,94,72,67,82,81,36,54,42,67] 
c = [95,89,71,69,82,79,51,60,45,66] 
d = [94,87,79,65,89,81,42,63,43,64] 
e = [97,100,65,69,86,84,40,55,40,60] 
df = [a,b,c,d,e] 
df1 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP','Math']) 
print(df1) 
print("Variance, subject wise") 
print(df1.var(axis = 1)) 


       0    1   2   3   4   5   6   7   8   9
Acct  99   94  81  70  88  90  41  61  42  68
Eco   94   94  72  67  82  81  36  54  42  67
Eng   95   89  71  69  82  79  51  60  45  66
IP    94   87  79  65  89  81  42  63  43  64
Math  97  100  65  69  86  84  40  55  40  60
Variance, subject wise
Acct    428.488889
Eco     402.544444
Eng     256.677778
IP      338.455556
Math    470.044444
dtype: float64


In [139]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print("Variance of each product:")
print(g.var(axis = 1))

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
Variance of each product:
Andhra P.    1.504662e+07
Gujarat      2.623096e+07
Kerala       1.839865e+06
Punjab       4.857210e+07
Tripura      1.571330e+05
Uttar p.     4.026830e+09
dtype: float64


### The describe() Function

In [140]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.describe()) 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
               Rice         Wheat       Pulses         Fruits
count      6.000000      4.000000     6.000000       6.000000
mean    6323.833333  12308.500000   665.216667   27876.400000
std     5462.454504  13846.150566   854.872997   55208.911975
min      814.600000      0.500000     1.700000      44.100000
25%     2048.700000   2052.875000    25.650000    1872.825000
50%     4929.100000   9588.750000   425.500000    7491.000000
75%    10553.000000  19844.375000   902.750000   10920.000000
max    13754.000000  30056.000000  2184.400000  140169.200000


### Function describe() for String type columns.

In [2]:
import pandas as pd 
s = pd.DataFrame({'0':['This','is','good','This','is fun']})
print(s) 
print(s.describe()) 


        0
0    This
1      is
2    good
3    This
4  is fun
           0
count      5
unique     4
top     This
freq       2


In [19]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88] 
b = [94,94,72,67,82] 
c = [95,89,71,69,82] 
df = [a,b,c] 
df1 = pd.DataFrame(df, columns = ['A','B','C','D','E']) 
print(df1) 
print(df1.describe(include='all')) 

    A   B   C   D   E
0  99  94  81  70  88
1  94  94  72  67  82
2  95  89  71  69  82
               A          B          C          D          E
count   3.000000   3.000000   3.000000   3.000000   3.000000
mean   96.000000  92.333333  74.666667  68.666667  84.000000
std     2.645751   2.886751   5.507571   1.527525   3.464102
min    94.000000  89.000000  71.000000  67.000000  82.000000
25%    94.500000  91.500000  71.500000  68.000000  82.000000
50%    95.000000  94.000000  72.000000  69.000000  82.000000
75%    97.000000  94.000000  76.500000  69.500000  85.000000
max    99.000000  94.000000  81.000000  70.000000  88.000000


### Inspection Function info()

In [20]:
a = [99,94,81,70,88,90,41,61,42,68] 
b = [94,94,72,67,82,81,36,54,42,67] 
c = [95,89,71,69,82,79,51,60,45,66] 
d = [94,87,79,65,89,81,42,63,43,64] 
e = [97,100,65,69,86,84,40,55,40,60] 
df = [a,b,c,d,e] 
df5 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP','Math']) 
print(df5) 
print(df5.info())

       0    1   2   3   4   5   6   7   8   9
Acct  99   94  81  70  88  90  41  61  42  68
Eco   94   94  72  67  82  81  36  54  42  67
Eng   95   89  71  69  82  79  51  60  45  66
IP    94   87  79  65  89  81  42  63  43  64
Math  97  100  65  69  86  84  40  55  40  60
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Acct to Math
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
 1   1       5 non-null      int64
 2   2       5 non-null      int64
 3   3       5 non-null      int64
 4   4       5 non-null      int64
 5   5       5 non-null      int64
 6   6       5 non-null      int64
 7   7       5 non-null      int64
 8   8       5 non-null      int64
 9   9       5 non-null      int64
dtypes: int64(10)
memory usage: 440.0+ bytes
None


In [21]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.info())

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Andhra P. to Uttar p.
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Rice    6 non-null      float64
 1   Wheat   4 non-null      float64
 2   Pulses  6 non-null      float64
 3   Fruits  6 non-null      float64
dtypes: float64(4)
memory usage: 240.0+ bytes
None


#### DataFrame's Top and Bottom Rows using head() and tail() 

In [24]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.tail()) 
print(g.head(n = 3))

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
             Rice    Wheat  Pulses    Fruits
Gujarat    1930.0   2737.0   818.0   11950.0
Kerala     2404.8      NaN     1.7     113.1
Punjab    11586.2  16440.5    33.0    7152.0
Tripura     814.6      0.5    23.2      44.1
Uttar p.  13754.0  30056.0  2184.4  140169.2
             Rice   Wheat  Pulses   Fruits
Andhra P.  7453.4     NaN   931.0   7830.0
Gujarat    1930.0  2737.0   818.0  11950.0
Kerala     2404.8     NaN     1.7    113.1


Example 24: Given dataframe dtf6. Write a program to display top two rows' values of 'Schools' column and last 3 values of 'Hospitals' column.

In [33]:
import pandas as pd  
import numpy as np  
a = [189,7916] 
b = [208,8508] 
c = [149,7226] 
d = [157,7617] 
e = [a,b,c,d] 
s = pd.DataFrame(e, index = ['Delhi','Mumbai','Kolkata','Chennai'], columns=
                ['Hospitals','Schools']) 
print(s) 
print(s.Hospitals.head(2)) 
print(s.Schools.tail(3)) 


         Hospitals  Schools
Delhi          189     7916
Mumbai         208     8508
Kolkata        149     7226
Chennai        157     7617
Delhi     189
Mumbai    208
Name: Hospitals, dtype: int64
Mumbai     8508
Kolkata    7226
Chennai    7617
Name: Schools, dtype: int64


### Cumulative Calculations Funcctions

#### cumsum() Function

In [35]:
a = [9,18,27] 
b = [36,45,54] 
c = [63,72,81] 
d = [a,b,c] 
m = pd.DataFrame(d, columns = ['A','B','C']) 
print(m)

    A   B   C
0   9  18  27
1  36  45  54
2  63  72  81


In [37]:
print(m.cumsum()) 
print(m.cumsum(axis = 'rows'))

     A    B    C
0    9   18   27
1   45   63   81
2  108  135  162
     A    B    C
0    9   18   27
1   45   63   81
2  108  135  162


In [38]:
print(m.cumsum(axis = 'columns')) 

    A    B    C
0   9   27   54
1  36   81  135
2  63  135  216


#### cumprod(), cummax(), cummin() Functions

Example 25: Consider above given team points dataframe df1 and df2 , write a program to list maximum points till that round(cumlatively).

In [4]:
import pandas as pd 
a = {'p1':[700,975,970,900],'p2':[490,460,570,590]} 
team1 = pd.DataFrame(a)  
b = {'p1':[1100,1275,1270,1400],'p2':[1400,1260,1500,1190]} 
team2 = pd.DataFrame(b) 
print("Cumulative max. points till each round:") 
print(team1)
print(team1.cummax()) 
print(team2)
print(team2.cummax()) 


Cumulative max. points till each round:
    p1   p2
0  700  490
1  975  460
2  970  570
3  900  590
    p1   p2
0  700  490
1  975  490
2  975  570
3  975  590
     p1    p2
0  1100  1400
1  1275  1260
2  1270  1500
3  1400  1190
     p1    p2
0  1100  1400
1  1275  1400
2  1275  1500
3  1400  1500


Example 26: Considering dataframe of team2's points, write a program to print  the total points of each player till each row.

In [6]:
import pandas as pd 
a = {'p1':[700,975,970,900],'p2':[490,460,570,590]} 
team1 = pd.DataFrame(a)  
b = {'p1':[1100,1275,1270,1400],'p2':[1400,1260,1500,1190]} 
team2 = pd.DataFrame(b) 
print(team2)
print("Cumulative total points till each round:") 
print(team2.cumsum()) 

     p1    p2
0  1100  1400
1  1275  1260
2  1270  1500
3  1400  1190
Cumulative total points till each round:
     p1    p2
0  1100  1400
1  2375  2660
2  3645  4160
3  5045  5350


Example 27: Consider the dataframe prodf that stores some agricultural statistics of some Indian states. Write a program to find out how many states produce Wheat crop.

### Examples only till 32

import pandas as pd  
import numpy as np 
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print("Wheat crop produced by", g['Wheat'].count(), 'states.') 


Example 28: Consider the dataframe prodf that stores some agricultural statistics of some Indian states. Write a program to find out how many states produce Wheat crop and how many produce the Rice crop

In [11]:
import pandas as pd  
import numpy as np 
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print("Wheat crop produced by in these many states")
print(g[['Wheat','Rice']].count(), 'states.') 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
Wheat crop produced by in these many states
Wheat    4
Rice     6
dtype: int64 states.


Example 29: Consider the dataframe prodf that stores some agricultural statistics of some Indian states. Write a program to find out how many states produce Wheat crops are produced by the state Andhra Pradesh

In [12]:
import pandas as pd  
import numpy as np 
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(" Crops produced by Andhra Pradesh are") 
print(g.loc['Andhra P.', :].count()) 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
 Crops produced by Andhra Pradesh are
3


Example 30: Consider the dataframe dfmks given. Write a program to count how many exams were conducted for each section.

In [22]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88] 
b = [94,None,72,67,82] 
c = [95,89,71,None,82] 
d = [94,87,79,65,89] 
df = [a,b,c,d] 
df1 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP']) 
print(df1)
print('Exams were conducted by each section are.') 
print(df1.iloc[:, :].count())

       0     1   2     3   4
Acct  99  94.0  81  70.0  88
Eco   94   NaN  72  67.0  82
Eng   95  89.0  71   NaN  82
IP    94  87.0  79  65.0  89
Exams were conducted by each section are.
0    4
1    3
2    4
3    3
4    4
dtype: int64


Example 31: Consider the dataframe dfmks given. Write a program to list subject wise about how many sections took exam of that subject.

In [25]:
import pandas as pd 
import numpy as np 
a = [99,94,81,70,88] 
b = [94,56,72,67,82] 
c = [95,None,71,98,82] 
d = [94,87,None,65,89] 
df = [a,b,c,d] 
df1 = pd.DataFrame(df, index = ['Acct','Eco','Eng','IP']) 
print(df1) 
print("Exams were conducted by each section are.") 
print(df1.iloc[:, :].count(axis = 1))

       0     1     2   3   4
Acct  99  94.0  81.0  70  88
Eco   94  56.0  72.0  67  82
Eng   95   NaN  71.0  98  82
IP    94  87.0   NaN  65  89
Exams were conducted by each section are.
Acct    5
Eco     5
Eng     4
IP      4
dtype: int64


Example 32: Consider dataframe prod given earlier. There are six states listed. Write a program to print maximum produce of the middle 2 states listed (Kerala and Punjab)

In [28]:
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
prodf = pd.DataFrame(iprod) 
print(prodf) 
print('Maximum produced by Kerala and Punjab:') 
print(prodf.iloc[2:4, :].max(axis = 1))

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
Maximum produced by Kerala and Punjab:
Kerala     2404.8
Punjab    16440.5
dtype: float64


## Advanced Operations on DataFrame

### Pivoting

In [11]:
#Syntax:<df>.pivot(index='<columnname>', columns='<columnname>',values='<columnname>')
import pandas as pd  
d1 = { 'Classes':[28,36,41,32,40],'Country':['USA','UK','Japan','USA','Brazil'],
                          'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat']}
                                                             
dfd = pd.DataFrame(d1) 
print(dfd) 
print(dfd.pivot(index = 'Country', columns='Tutor', values='Classes')) 

   Classes Country    Tutor
0       28     USA   Tahira
1       36      UK  Gurjyot
2       41   Japan   Anusha
3       32     USA    Jacob
4       40  Brazil   Venkat
Tutor    Anusha  Gurjyot  Jacob  Tahira  Venkat
Country                                        
Brazil      NaN      NaN    NaN     NaN    40.0
Japan      41.0      NaN    NaN     NaN     NaN
UK          NaN     36.0    NaN     NaN     NaN
USA         NaN      NaN   32.0    28.0     NaN


In [12]:
print(dfd.pivot(index = 'Tutor', columns= 'Country')) 

        Classes                  
Country  Brazil Japan    UK   USA
Tutor                            
Anusha      NaN  41.0   NaN   NaN
Gurjyot     NaN   NaN  36.0   NaN
Jacob       NaN   NaN   NaN  32.0
Tahira      NaN   NaN   NaN  28.0
Venkat     40.0   NaN   NaN   NaN


Example 33: Consider a dataframe ndf as shown below. Write a program to summarise hoe many projects are handled by each position for each city.

In [17]:
s = {'Name':['Rabin','Evan','Jia','Lalit','Jaspreet','Sujal'],
     'Sex':['F','M','F','M','M','F'],
     'Position':['Manager','Programmer','Manager'
                                                ,'Manager','Programmer','Programmer'],
    'City':['Bangalore','New Delhi','Chennai','Mumbai','Chennai','Bangalore'],
     'Age':[30,27,32,40,28,32],'Projects':[13,17,16,20,21,14]}
df = pd.DataFrame(s) 
print(df)  

       Name Sex    Position       City  Age  Projects
0     Rabin   F     Manager  Bangalore   30        13
1      Evan   M  Programmer  New Delhi   27        17
2       Jia   F     Manager    Chennai   32        16
3     Lalit   M     Manager     Mumbai   40        20
4  Jaspreet   M  Programmer    Chennai   28        21
5     Sujal   F  Programmer  Bangalore   32        14


In [19]:
print(df.pivot(index = 'Position', columns='City', values='Projects')) 

City        Bangalore  Chennai  Mumbai  New Delhi
Position                                         
Manager          13.0     16.0    20.0        NaN
Programmer       14.0     21.0     NaN       17.0


Example 34: Consider the ndf of previous example, write a program to summarise information Position wise about how many projects are being handled by them for each city. Print zero() in case the data is missing for some column/row.

In [22]:
s = {'Name':['Rabin','Evan','Jia','Lalit','Jaspreet','Sujal'],
     'Sex':['F','M','F','M','M','F'],
     'Position':['Manager','Programmer','Manager'
                                                ,'Manager','Programmer','Programmer'],
    'City':['Bangalore','New Delhi','Chennai','Mumbai','Chennai','Bangalore'],
     'Age':[30,27,32,40,28,32],'Projects':[13,17,16,20,21,14]}
df = pd.DataFrame(s) 
print(df) 
print('*********************')
print(df.pivot(index = 'Position', columns='City', values='Projects').fillna(0)) 

       Name Sex    Position       City  Age  Projects
0     Rabin   F     Manager  Bangalore   30        13
1      Evan   M  Programmer  New Delhi   27        17
2       Jia   F     Manager    Chennai   32        16
3     Lalit   M     Manager     Mumbai   40        20
4  Jaspreet   M  Programmer    Chennai   28        21
5     Sujal   F  Programmer  Bangalore   32        14
*********************
City        Bangalore  Chennai  Mumbai  New Delhi
Position                                         
Manager          13.0     16.0    20.0        0.0
Programmer       14.0     21.0     0.0       17.0


In [27]:
on = {'Classes':[28,36,41,32,40,36,40,36,40,46,24,30,44,40,32,36,32,36,42,38],
           'Country':['USA','UK','Japan','USA','Brazil','USA','USA','Japan','Brazil',
                    'USA','Brazil','USA','UK','Brazil','USA','Japan','Japan',
                        'Brazil','UK','USA'],
      'Quarter':[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4],
      'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat']}
c = pd.DataFrame(on) 
print(c) 
# print(c.pivot(index='Tutor',columns='Country')) 

    Classes Country  Quarter    Tutor
0        28     USA        1   Tahira
1        36      UK        1  Gurjyot
2        41   Japan        1   Anusha
3        32     USA        1    Jacob
4        40  Brazil        1   Venkat
5        36     USA        2   Tahira
6        40     USA        2  Gurjyot
7        36   Japan        2   Anusha
8        40  Brazil        2    Jacob
9        46     USA        2   Venkat
10       24  Brazil        3   Tahira
11       30     USA        3  Gurjyot
12       44      UK        3   Anusha
13       40  Brazil        3    Jacob
14       32     USA        3   Venkat
15       36   Japan        4   Tahira
16       32   Japan        4  Gurjyot
17       36  Brazil        4   Anusha
18       42      UK        4    Jacob
19       38     USA        4   Venkat


### Pivot_table Function 

In [31]:
on = {'Classes':[28,36,41,32,40,36,40,36,40,46,24,30,44,40,32,36,32,36,42,38],
           'Country':['USA','UK','Japan','USA','Brazil','USA','USA','Japan','Brazil',
                    'USA','Brazil','USA','UK','Brazil','USA','Japan','Japan',
                        'Brazil','UK','USA'],
      'Quarter':[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4],
      'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat']}
c = pd.DataFrame(on) 
print(c) 
print(c.pivot_table(index='Tutor', columns='Country', values='Classes'))
print(c.pivot_table(index='Tutor', columns='Country', values='Classes').fillna(0)) 

    Classes Country  Quarter    Tutor
0        28     USA        1   Tahira
1        36      UK        1  Gurjyot
2        41   Japan        1   Anusha
3        32     USA        1    Jacob
4        40  Brazil        1   Venkat
5        36     USA        2   Tahira
6        40     USA        2  Gurjyot
7        36   Japan        2   Anusha
8        40  Brazil        2    Jacob
9        46     USA        2   Venkat
10       24  Brazil        3   Tahira
11       30     USA        3  Gurjyot
12       44      UK        3   Anusha
13       40  Brazil        3    Jacob
14       32     USA        3   Venkat
15       36   Japan        4   Tahira
16       32   Japan        4  Gurjyot
17       36  Brazil        4   Anusha
18       42      UK        4    Jacob
19       38     USA        4   Venkat
Country  Brazil  Japan    UK        USA
Tutor                                  
Anusha     36.0   38.5  44.0        NaN
Gurjyot     NaN   32.0  36.0  35.000000
Jacob      40.0    NaN  42.0  32.000000
Ta

Example 35: Consider the tutoring company data, compute tatal classes per tutor.

In [32]:
print(c.pivot_table(index='Tutor', values='Classes', aggfunc='sum')) 


         Classes
Tutor           
Anusha       157
Gurjyot      138
Jacob        154
Tahira       124
Venkat       156


Example 36:Consider the tutoring company data, compute number of countries per tutor

In [33]:
print(c.pivot_table(index='Tutor', values='Classes', aggfunc='count')) 

         Classes
Tutor           
Anusha         4
Gurjyot        4
Jacob          4
Tahira         4
Venkat         4


Example 37: Consider the tutoring company data, compute total classes by country.

In [34]:
print(c.pivot_table(index='Country', values='Classes', aggfunc='sum')) 

         Classes
Country         
Brazil       180
Japan        145
UK           122
USA          282


Example 38: Consider the tutoring company data, compute total classes on two fields, tutor and country wise. 

In [36]:
print(c.pivot_table(index = ['Tutor','Country'], values=['Classes'], aggfunc='sum'))  


                 Classes
Tutor   Country         
Anusha  Brazil        36
        Japan         77
        UK            44
Gurjyot Japan         32
        UK            36
        USA           70
Jacob   Brazil        80
        UK            42
        USA           32
Tahira  Brazil        24
        Japan         36
        USA           64
Venkat  Brazil        40
        USA          116


Example 39: Consider the tutoring company data, compute average classes on two fields. 

In [37]:
print(c.pivot_table(index=['Tutor','Country'], values=['Classes'], aggfunc='mean'))  


                   Classes
Tutor   Country           
Anusha  Brazil   36.000000
        Japan    38.500000
        UK       44.000000
Gurjyot Japan    32.000000
        UK       36.000000
        USA      35.000000
Jacob   Brazil   40.000000
        UK       42.000000
        USA      32.000000
Tahira  Brazil   24.000000
        Japan    36.000000
        USA      32.000000
Venkat  Brazil   40.000000
        USA      38.666667


### Sort_values Function

Example 40: Consider the prodf dataframe sorting crop production statistics of various states. Write a program to sort the values of prodf in the order of Wheat production by them.

In [41]:
import pandas as pd  
import numpy as np 
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.sort_values(by = ['Wheat']).fillna(0)) 


              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
              Rice    Wheat  Pulses    Fruits
Tripura      814.6      0.5    23.2      44.1
Gujarat     1930.0   2737.0   818.0   11950.0
Punjab     11586.2  16440.5    33.0    7152.0
Uttar p.   13754.0  30056.0  2184.4  140169.2
Andhra P.   7453.4      0.0   931.0    7830.0
Kerala      2404.8      0.0     1.7     113.1


Example 41: Consider the prodf dataframe sorting crop production statistics of various states. Write a program to sort the values of prodf in the order of Fruits production by them, in descending order.

In [44]:
print(g.sort_values(by = ['Fruits'], ascending = False).fillna(0)) 
      

              Rice    Wheat  Pulses    Fruits
Uttar p.   13754.0  30056.0  2184.4  140169.2
Gujarat     1930.0   2737.0   818.0   11950.0
Andhra P.   7453.4      0.0   931.0    7830.0
Punjab     11586.2  16440.5    33.0    7152.0
Kerala      2404.8      0.0     1.7     113.1
Tripura      814.6      0.5    23.2      44.1


Example 42: Consider the prodf dataframe sorting crop production statistics of various states. Write a program to sort the values of prodf in the order of indexes, in descending order.

In [45]:
print(g.sort_index(ascending=False))

              Rice    Wheat  Pulses    Fruits
Uttar p.   13754.0  30056.0  2184.4  140169.2
Tripura      814.6      0.5    23.2      44.1
Punjab     11586.2  16440.5    33.0    7152.0
Kerala      2404.8      NaN     1.7     113.1
Gujarat     1930.0   2737.0   818.0   11950.0
Andhra P.   7453.4      NaN   931.0    7830.0


### The mad() Function

In [58]:
import pandas as pd  
import numpy as np 
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g)  
# print(g.groupby()) 
# print(g.aggregate('mean')) 

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2


## Handling Missing Data

### Detecting/Filtering Missing Data

In [1]:
# Syntax: <PandaObject>.isnull() 
# Syntax: <series>[filter condition] 
import pandas as pd  
d1 = { 'Classes':[28,36,41,32,40],'Country':['USA','UK','Japan','USA','Brazil'],
                          'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat']}
                                                             
dfd = pd.DataFrame(d1) 
print(dfd) 
print(dfd.isnull())

   Classes Country    Tutor
0       28     USA   Tahira
1       36      UK  Gurjyot
2       41   Japan   Anusha
3       32     USA    Jacob
4       40  Brazil   Venkat
   Classes  Country  Tutor
0    False    False  False
1    False    False  False
2    False    False  False
3    False    False  False
4    False    False  False


In [4]:
import pandas as pd  
d1 = { 'Classes':[28,36,41,32,40],'Country':['USA','UK','Japan','USA','Brazil'],
                          'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat']}
                                                             
dfd = pd.Series(d1) 
print(dfd) 
print(dfd.isnull())

Classes                        [28, 36, 41, 32, 40]
Country               [USA, UK, Japan, USA, Brazil]
Tutor      [Tahira, Gurjyot, Anusha, Jacob, Venkat]
dtype: object
Classes    False
Country    False
Tutor      False
dtype: bool


In [6]:
import pandas as pd   
import numpy as np
iprod = {'Rice':{'Andhra P.':7453.4, 'Gujarat':1930.0, 'Kerala':2404.8,'Punjab':
                 11586.2, 'Tripura': 814.6, 'Uttar p.':13754.0},
          'Wheat':{'Andhra P.':np.NaN, 'Gujarat':2737.0, 'Kerala':np.NaN,'Punjab':
                 16440.5, 'Tripura': 0.5, 'Uttar p.':30056.0},
         'Pulses':{'Andhra P.':931.0, 'Gujarat':818.0, 'Kerala':1.7,'Punjab':
                 33.0, 'Tripura':23.2, 'Uttar p.':2184.4},
         'Fruits':{'Andhra P.':7830.0, 'Gujarat':11950.0, 'Kerala':113.1,'Punjab':
                 7152.0, 'Tripura':44.1, 'Uttar p.':140169.2}} 
g = pd.DataFrame(iprod) 
print(g) 
print(g.isnull())

              Rice    Wheat  Pulses    Fruits
Andhra P.   7453.4      NaN   931.0    7830.0
Gujarat     1930.0   2737.0   818.0   11950.0
Kerala      2404.8      NaN     1.7     113.1
Punjab     11586.2  16440.5    33.0    7152.0
Tripura      814.6      0.5    23.2      44.1
Uttar p.   13754.0  30056.0  2184.4  140169.2
            Rice  Wheat  Pulses  Fruits
Andhra P.  False   True   False   False
Gujarat    False  False   False   False
Kerala     False   True   False   False
Punjab     False  False   False   False
Tripura    False  False   False   False
Uttar p.   False  False   False   False


### Handling Missing Data- Dropping Missing Values 

In [11]:
# Syntax: <PandaObject>.dropna().This will drop all rows having NaN value even 
# with a single NaN

s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
print("*******************")
print(ptdf.dropna())

  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
*******************
  First Name Last Name   Age Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0   m          4.0      25.0
3     Ruhana     Singh  24.0   m          2.0      62.0
4       Mike      John  73.0   f          3.0      70.0


In [12]:
# Syntax: pdObject.dropna(how = 'all'). it will remove only that row which have 
# all NaN values. 
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
print("*******************")
print(ptdf.dropna(how='all'))

  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
*******************
  First Name Last Name   Age Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0   m          4.0      25.0
2       Ruhi      Hyat  36.0   f          NaN       NaN
3     Ruhana     Singh  24.0   m          2.0      62.0
4       Mike      John  73.0   f          3.0      70.0


In [13]:
# Syntax: <pdobject>.dropna(axis=1). will drop all the columns which have any NaN 
# values in them. 
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
print("*******************")
print(ptdf.dropna(axis = 1))

  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
*******************
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]


### Handling Missing Values-Filling Missing values

In [14]:
# Syntax: <pdobject>.fillna(<n>) 
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
print(ptdf.fillna(0))

  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
  First Name Last Name   Age Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0   m          4.0      25.0
1          0         0   0.0   0          0.0       0.0
2       Ruhi      Hyat  36.0   f          0.0       0.0
3     Ruhana     Singh  24.0   m          2.0      62.0
4       Mike      John  73.0   f          3.0      70.0


In [17]:
# If you want to make change in dataframe also then you have to write. 
# Syntax: <pdobject>.fillna(0, inplace=True) 
# This arguement will make change in the original dataframe
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
print(ptdf.fillna(0, inplace = True)) 
print('@@@@@@@@@@@@@@@@@@@@@@@@@@')
print(ptdf) 


  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
None
@@@@@@@@@@@@@@@@@@@@@@@@@@
  First Name Last Name   Age Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0   m          4.0      25.0
1          0         0   0.0   0          0.0       0.0
2       Ruhi      Hyat  36.0   f          0.0       0.0
3     Ruhana     Singh  24.0   m          2.0      62.0
4       Mike      John  73.0   f          3.0      70.0


In [19]:
# You can use dictionary also in case. 
# Syntax: fillvalues={'Key':'Value'} 
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
fillvalues = {'First Name':'x','Last Name':'x','Age':'0','Sex':'x',
                    'ValueBefore':'-999','ValueAfter':'-999'} 
ptd = ptdf.fillna(fillvalues) 
print(ptd)

  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
  First Name Last Name   Age Sex ValueBefore  ValAfter
0      Jivin     Arora  42.0   m         4.0      25.0
1          x         x     0   x        -999       NaN
2       Ruhi      Hyat  36.0   f        -999       NaN
3     Ruhana     Singh  24.0   m         2.0      62.0
4       Mike      John  73.0   f         3.0      70.0


In [24]:
# It can fill some one or two also whatever you will have to change
s = {'First Name':['Jivin',None,'Ruhi','Ruhana','Mike'],'Last Name':['Arora',None,'Hyat' 
,'Singh','John'], 'Age':[42,None,36,24,73],'Sex':['m',None,'f','m','f'],
     'ValueBefore':[4,None,None,2,3], 'ValAfter':[25,None,None,62,70]} 
ptdf=pd.DataFrame(s) 
print(ptdf) 
pt = ptdf.fillna({'Age': 0,'Sex':'x'})
print(pt) 


  First Name Last Name   Age   Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0     m          4.0      25.0
1       None      None   NaN  None          NaN       NaN
2       Ruhi      Hyat  36.0     f          NaN       NaN
3     Ruhana     Singh  24.0     m          2.0      62.0
4       Mike      John  73.0     f          3.0      70.0
  First Name Last Name   Age Sex  ValueBefore  ValAfter
0      Jivin     Arora  42.0   m          4.0      25.0
1       None      None   0.0   x          NaN       NaN
2       Ruhi      Hyat  36.0   f          NaN       NaN
3     Ruhana     Singh  24.0   m          2.0      62.0
4       Mike      John  73.0   f          3.0      70.0


Example 43: Consider the dataframe dfmks having some missing values as shown below. 
Write a program to fill the missing values with value(0)

In [28]:
a = [99,94.0,92,97.0] 
b = [90,94.0,92,97.0] 
c = [95,89.0,91,89.0] 
d = [94,None,99,95.0] 
e = [97,100.0,99,None] 
f = [a,b,c,d,e] 
s = pd.DataFrame(f, index = ['Acct','Eco','Eng','IP','Math'],
                columns=['A','B','C','D']) 
print(s)
print("****************************")
print("DataFrame after filing the missing data")
print(s.fillna(0))

       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    NaN  99  95.0
Math  97  100.0  99   NaN
****************************
DataFrame after filing the missing data
       A      B   C     D
Acct  99   94.0  92  97.0
Eco   90   94.0  92  97.0
Eng   95   89.0  91  89.0
IP    94    0.0  99  95.0
Math  97  100.0  99   0.0


In [35]:
# If you want to fill the from another dataframe then you can use this syntax but
# both the dataframes should have same column and row. 
#Syntax:Df1.fillna(Df2) 


## Combining DataFrames

In [5]:
import pandas as pd
s = {'Subject_id':[1,2,3,4,5],'First_Name':['Sarah','Reet','Robert','Zakir','Jia'],
     'Last_Name':['Kapur','Kaur','Tiloda','Ali','Taneja'] } 
a = pd.DataFrame(s) 
print(a)

   Subject_id First_Name Last_Name
0           1      Sarah     Kapur
1           2       Reet      Kaur
2           3     Robert    Tiloda
3           4      Zakir       Ali
4           5        Jia    Taneja


In [7]:
import pandas as pd 
d = {'Subject_id':[4,5,6,7,8],'First_Name':['Ayushi','Minakshi','Kajal','Sweta','Jaan'],
     'Last_Name':['Thakur','Singhaniya','Rajput','Sweet','Khadoos']} 
b = pd.DataFrame(d) 
print(b)

   Subject_id First_Name   Last_Name
0           4     Ayushi      Thakur
1           5   Minakshi  Singhaniya
2           6      Kajal      Rajput
3           7      Sweta       Sweet
4           8       Jaan     Khadoos


In [6]:
import pandas as pd 
s = {'Sub_id':[1,2,3,4,5,6,7,8,9,10],'Test_id':[51,15,15,61,16,14,15,1,61,16]} 
c = pd.DataFrame(s) 
print(c)

   Sub_id  Test_id
0       1       51
1       2       15
2       3       15
3       4       61
4       5       16
5       6       14
6       7       15
7       8        1
8       9       61
9      10       16


### The concat() Function

In [14]:
s = pd.concat([a,b]) 
print(s)

   Subject_id First_Name   Last_Name
0           1      Sarah       Kapur
1           2       Reet        Kaur
2           3     Robert      Tiloda
3           4      Zakir         Ali
4           5        Jia      Taneja
0           4     Ayushi      Thakur
1           5   Minakshi  Singhaniya
2           6      Kajal      Rajput
3           7      Sweta       Sweet
4           8       Jaan     Khadoos


In [13]:
d = pd.concat([a,b,], axis = 1) 
print(d)


   Subject_id First_Name Last_Name  Subject_id First_Name   Last_Name
0           1      Sarah     Kapur           4     Ayushi      Thakur
1           2       Reet      Kaur           5   Minakshi  Singhaniya
2           3     Robert    Tiloda           6      Kajal      Rajput
3           4      Zakir       Ali           7      Sweta       Sweet
4           5        Jia    Taneja           8       Jaan     Khadoos


Example 44: Write a program to concat above used datafram along the rows but ensure that the new indexes are generated in the resultant dataframe.

In [15]:
g = pd.concat([a,b],ignore_index=True) 
print(g)

   Subject_id First_Name   Last_Name
0           1      Sarah       Kapur
1           2       Reet        Kaur
2           3     Robert      Tiloda
3           4      Zakir         Ali
4           5        Jia      Taneja
5           4     Ayushi      Thakur
6           5   Minakshi  Singhaniya
7           6      Kajal      Rajput
8           7      Sweta       Sweet
9           8       Jaan     Khadoos


### Combining DataFrames using join()

In [32]:
c = {'Name':['Harini','Dave','Simrat','Saqib']} 
D1 = pd.DataFrame(c)  
print(D1)




     Name
0  Harini
1    Dave
2  Simrat
3   Saqib


In [31]:
d = {'Competitions':[5,3,3]} 
D2 = pd.DataFrame(d) 
print(D2)

   Competitions
0             5
1             3
2             3


In [36]:
print(D1.join(D2, how = 'outer')) 
print(D1.join(D2, how = 'inner')) 
print(D1.join(D2, how = 'left')) 
print(D1.join(D2, how = 'right')) 



     Name  Competitions
0  Harini           5.0
1    Dave           3.0
2  Simrat           3.0
3   Saqib           NaN
     Name  Competitions
0  Harini             5
1    Dave             3
2  Simrat             3
     Name  Competitions
0  Harini           5.0
1    Dave           3.0
2  Simrat           3.0
3   Saqib           NaN
     Name  Competitions
0  Harini             5
1    Dave             3
2  Simrat             3


In [40]:
print(D2.join(D1, how = 'outer')) 
print(D2.join(D1, how = 'inner')) 
print(D2.join(D1, how = 'left')) 
print(D2.join(D1, how = 'right')) 


   Competitions    Name
0           5.0  Harini
1           3.0    Dave
2           3.0  Simrat
3           NaN   Saqib
   Competitions    Name
0             5  Harini
1             3    Dave
2             3  Simrat
   Competitions    Name
0             5  Harini
1             3    Dave
2             3  Simrat
   Competitions    Name
0           5.0  Harini
1           3.0    Dave
2           3.0  Simrat
3           NaN   Saqib


In [2]:
h = {'Target':[56000,70000,75000,60000],'Sales':[58000,68000,78000,61000]} 
sal = pd.DataFrame(h, index = ['zoneA','zoneB','zoneC','zoneD']) 
print(sal)  
j = {'Name':['Purv','Paschim','Kendriya','Dakshin','Uttar','Rural'],
    'Product':['Oven','AC','AC','Oven','TV','Tubewell']}  
sal1 = pd.DataFrame(j, index = ['zoneA','zoneB','zoneC','zoneD','zoneE','zoneF']) 
print(sal1)

       Target  Sales
zoneA   56000  58000
zoneB   70000  68000
zoneC   75000  78000
zoneD   60000  61000
           Name   Product
zoneA      Purv      Oven
zoneB   Paschim        AC
zoneC  Kendriya        AC
zoneD   Dakshin      Oven
zoneE     Uttar        TV
zoneF     Rural  Tubewell


Example 45: Write a program to create a dataframe namely df1 that stores all the rows of df2 and only the matching indexes rows from saledf2.

In [3]:
import pandas as pd  
print(sal1.join(sal)) 


           Name   Product   Target    Sales
zoneA      Purv      Oven  56000.0  58000.0
zoneB   Paschim        AC  70000.0  68000.0
zoneC  Kendriya        AC  75000.0  78000.0
zoneD   Dakshin      Oven  60000.0  61000.0
zoneE     Uttar        TV      NaN      NaN
zoneF     Rural  Tubewell      NaN      NaN


Example 46: Write a program to create a dataframe namely df1 that stores only the matching indexes rows from both sal and sal1.

In [4]:
import pandas as pd  
print(sal1.join(sal, how = 'inner')) 


           Name Product  Target  Sales
zoneA      Purv    Oven   56000  58000
zoneB   Paschim      AC   70000  68000
zoneC  Kendriya      AC   75000  78000
zoneD   Dakshin    Oven   60000  61000


In [8]:
j = {'cust_id':[1,2,3,4,5,6],
    'Product':['Oven','AC','AC','Oven','TV','Tubewell']}  
sal5 = pd.DataFrame(j) 
print(sal5) 
k = {'p_id':[2,4,6],'State':["Delhi","Goa","Kerala"]} 
sal4 = pd.DataFrame(k) 
print(sal4)

   cust_id   Product
0        1      Oven
1        2        AC
2        3        AC
3        4      Oven
4        5        TV
5        6  Tubewell
   p_id   State
0     2   Delhi
1     4     Goa
2     6  Kerala


In [14]:
# Joining on a column 
print(sal4.join(sal5))
print(sal5.join(sal4, on = 'cust_id')) 
print(sal4.join(sal5, on = 'p_id')) 



   p_id   State  cust_id Product
0     2   Delhi        1    Oven
1     4     Goa        2      AC
2     6  Kerala        3      AC
   cust_id   Product  p_id   State
0        1      Oven   4.0     Goa
1        2        AC   6.0  Kerala
2        3        AC   NaN     NaN
3        4      Oven   NaN     NaN
4        5        TV   NaN     NaN
5        6  Tubewell   NaN     NaN
   p_id   State  cust_id Product
0     2   Delhi      3.0      AC
1     4     Goa      5.0      TV
2     6  Kerala      NaN     NaN


### Combining DataFrames using merge() Function

In [22]:
j = {'cust_id':[1,2,3,4,5,6],
    'Product':['Oven','AC','AC','Oven','TV','Tubewell']}  
sal5 = pd.DataFrame(j) 
print(sal5) 
k = {'p_id':[2,4,6],'State':["Delhi","Goa","Kerala"]} 
sal4 = pd.DataFrame(k) 
print(sal4)
# print(pd.merge(sal5,sal4, on = 'cust_id', how = 'all')) 
# print(p)

   cust_id   Product
0        1      Oven
1        2        AC
2        3        AC
3        4      Oven
4        5        TV
5        6  Tubewell
   p_id   State
0     2   Delhi
1     4     Goa
2     6  Kerala


In [24]:
l = {'cust_id':[1,2,3,4,5],'F_Name':['Jaan','Cutie','Sweetie','Angry_Bird','Khadoos'],
     'last_name':['Singh','Bevli','Khurana','Gadkary','Jaan'],'email':
     ['s@gak.com','bev@.com','rana@.com','Gad@.com','Jaan@s.com'] }
cust = pd.DataFrame(l) 
print(cust)

   cust_id      F_Name last_name       email
0        1        Jaan     Singh   s@gak.com
1        2       Cutie     Bevli    bev@.com
2        3     Sweetie   Khurana   rana@.com
3        4  Angry_Bird   Gadkary    Gad@.com
4        5     Khadoos      Jaan  Jaan@s.com


In [25]:
u = {'order_id':[1,2,3,4,5,6],'amount':[23234.56,62378.50,32124.00,8365.50,12325.50,
                                       12614.40],'cust_id':[1,3,2,3,10,9]} 
order = pd.DataFrame(u) 
print(order)


   order_id    amount  cust_id
0         1  23234.56        1
1         2  62378.50        3
2         3  32124.00        2
3         4   8365.50        3
4         5  12325.50       10
5         6  12614.40        9


Example 47: Write a program a create a merged dataframe using the cust and order dataframes, which is merged on common field cust_id and contains only the rows having matching cust_id values.

In [27]:
l = {'cust_id':[1,2,3,4,5],'F_Name':['Jaan','Cutie','Sweetie','Angry_Bird','Khadoos'],
     'last_name':['Singh','Bevli','Khurana','Gadkary','Jaan'],'email':
     ['s@gak.com','bev@.com','rana@.com','Gad@.com','Jaan@s.com'] }
cust = pd.DataFrame(l) 
print(cust)
u = {'order_id':[1,2,3,4,5,6],'amount':[23234.56,62378.50,32124.00,8365.50,12325.50,
                                       12614.40],'cust_id':[1,3,2,3,10,9]} 
order = pd.DataFrame(u) 
print(order)
res0 = pd.merge(order, cust, on = 'cust_id') 
print(res0)

   cust_id      F_Name last_name       email
0        1        Jaan     Singh   s@gak.com
1        2       Cutie     Bevli    bev@.com
2        3     Sweetie   Khurana   rana@.com
3        4  Angry_Bird   Gadkary    Gad@.com
4        5     Khadoos      Jaan  Jaan@s.com
   order_id    amount  cust_id
0         1  23234.56        1
1         2  62378.50        3
2         3  32124.00        2
3         4   8365.50        3
4         5  12325.50       10
5         6  12614.40        9
   order_id    amount  cust_id   F_Name last_name      email
0         1  23234.56        1     Jaan     Singh  s@gak.com
1         2  62378.50        3  Sweetie   Khurana  rana@.com
2         3  32124.00        2    Cutie     Bevli   bev@.com
3         4   8365.50        3  Sweetie   Khurana  rana@.com


Example 48: Write a program a create a merged dataframe using the cust and order dataframes, which is merged on common field cust_id and contains all the rows from order dataframe and from cust dataframe, only the rows having matching cust_id 

In [28]:
l = {'cust_id':[1,2,3,4,5],'F_Name':['Jaan','Cutie','Sweetie','Angry_Bird','Khadoos'],
     'last_name':['Singh','Bevli','Khurana','Gadkary','Jaan'],'email':
     ['s@gak.com','bev@.com','rana@.com','Gad@.com','Jaan@s.com'] }
cust = pd.DataFrame(l) 
print(cust)
u = {'order_id':[1,2,3,4,5,6],'amount':[23234.56,62378.50,32124.00,8365.50,12325.50,
                                       12614.40],'cust_id':[1,3,2,3,10,9]} 
order = pd.DataFrame(u) 
print(order)
res = pd.merge(order, cust, on = 'cust_id', how = 'left') 
print(res)

   cust_id      F_Name last_name       email
0        1        Jaan     Singh   s@gak.com
1        2       Cutie     Bevli    bev@.com
2        3     Sweetie   Khurana   rana@.com
3        4  Angry_Bird   Gadkary    Gad@.com
4        5     Khadoos      Jaan  Jaan@s.com
   order_id    amount  cust_id
0         1  23234.56        1
1         2  62378.50        3
2         3  32124.00        2
3         4   8365.50        3
4         5  12325.50       10
5         6  12614.40        9
   order_id    amount  cust_id   F_Name last_name      email
0         1  23234.56        1     Jaan     Singh  s@gak.com
1         2  62378.50        3  Sweetie   Khurana  rana@.com
2         3  32124.00        2    Cutie     Bevli   bev@.com
3         4   8365.50        3  Sweetie   Khurana  rana@.com
4         5  12325.50       10      NaN       NaN        NaN
5         6  12614.40        9      NaN       NaN        NaN


Example 48: Write a program a create a merged dataframe using the cust and order dataframes, which is merged on common field cust_id and contains all the rows from order dataframe and from cust dataframe.

In [30]:
l = {'cust_id':[1,2,3,4,5],'F_Name':['Jaan','Cutie','Sweetie','Angry_Bird','Khadoos'],
     'last_name':['Singh','Bevli','Khurana','Gadkary','Jaan'],'email':
     ['s@gak.com','bev@.com','rana@.com','Gad@.com','Jaan@s.com'] }
cust = pd.DataFrame(l) 
print(cust)
u = {'order_id':[1,2,3,4,5,6],'amount':[23234.56,62378.50,32124.00,8365.50,12325.50,
                                       12614.40],'cust_id':[1,3,2,3,10,9]} 
order = pd.DataFrame(u) 
print(order)
res1 = pd.merge(order, cust, on = 'cust_id', how = 'outer') 
print(res1)

   cust_id      F_Name last_name       email
0        1        Jaan     Singh   s@gak.com
1        2       Cutie     Bevli    bev@.com
2        3     Sweetie   Khurana   rana@.com
3        4  Angry_Bird   Gadkary    Gad@.com
4        5     Khadoos      Jaan  Jaan@s.com
   order_id    amount  cust_id
0         1  23234.56        1
1         2  62378.50        3
2         3  32124.00        2
3         4   8365.50        3
4         5  12325.50       10
5         6  12614.40        9
   order_id    amount  cust_id      F_Name last_name       email
0       1.0  23234.56        1        Jaan     Singh   s@gak.com
1       3.0  32124.00        2       Cutie     Bevli    bev@.com
2       2.0  62378.50        3     Sweetie   Khurana   rana@.com
3       4.0   8365.50        3     Sweetie   Khurana   rana@.com
4       NaN       NaN        4  Angry_Bird   Gadkary    Gad@.com
5       NaN       NaN        5     Khadoos      Jaan  Jaan@s.com
6       6.0  12614.40        9         NaN       NaN      

## Function groupby()

In [39]:
# Syntax: <df>.groupby(by = None, axis = 0) 
on = {'Classes':[28,36,41,32,40,36,40,36,40,46,24,30,44,40,32,36,32,36,42,38],
           'Country':['USA','UK','Japan','USA','Brazil','USA','USA','Japan','Brazil',
                    'USA','Brazil','USA','UK','Brazil','USA','Japan','Japan',
                        'Brazil','UK','USA'],
      'Quarter':[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4],
      'Tutor':['Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat',
                  'Tahira','Gurjyot','Anusha','Jacob','Venkat']}
c = pd.DataFrame(on) 
print(c)  
print('*********************')
gdf = c.groupby('Tutor') 
print(gdf)

    Classes Country  Quarter    Tutor
0        28     USA        1   Tahira
1        36      UK        1  Gurjyot
2        41   Japan        1   Anusha
3        32     USA        1    Jacob
4        40  Brazil        1   Venkat
5        36     USA        2   Tahira
6        40     USA        2  Gurjyot
7        36   Japan        2   Anusha
8        40  Brazil        2    Jacob
9        46     USA        2   Venkat
10       24  Brazil        3   Tahira
11       30     USA        3  Gurjyot
12       44      UK        3   Anusha
13       40  Brazil        3    Jacob
14       32     USA        3   Venkat
15       36   Japan        4   Tahira
16       32   Japan        4  Gurjyot
17       36  Brazil        4   Anusha
18       42      UK        4    Jacob
19       38     USA        4   Venkat
*********************


In [40]:
print(gdf.get_group('Venkat')) 

    Classes Country  Quarter   Tutor
4        40  Brazil        1  Venkat
9        46     USA        2  Venkat
14       32     USA        3  Venkat
19       38     USA        4  Venkat


In [42]:
print(gdf.get_group('Gurjyot' ))  

    Classes Country  Quarter    Tutor
1        36      UK        1  Gurjyot
6        40     USA        2  Gurjyot
11       30     USA        3  Gurjyot
16       32   Japan        4  Gurjyot


In [43]:
print(gdf.size()) 

Tutor
Anusha     4
Gurjyot    4
Jacob      4
Tahira     4
Venkat     4
dtype: int64


In [44]:
print(gdf.count())

         Classes  Country  Quarter
Tutor                             
Anusha         4        4        4
Gurjyot        4        4        4
Jacob          4        4        4
Tahira         4        4        4
Venkat         4        4        4


Example 50: Create a dataframe QtrSales where each row contains the item category, item name, and expenditure. Group the rows by the category, and print total expenditure per category.

In [48]:
import pandas as pd  
QtrSales = pd.DataFrame({'Item Category':['A','B','A','A','B','C','B','C'],
                         'Item Name':['ipad','LCD','iphone','iwatch','Projector',
                                     'Hard disk','Smartboard','Pen drive'],
                         'Expenditure':[288000,356000,497000,315000,413000,45000,
                                       211000,21000]})  
print(QtrSales)
print("Total expenditure category wise :") 
print(QtrSales.groupby("Item Category")["Expenditure"].sum()) 


  Item Category   Item Name  Expenditure
0             A        ipad       288000
1             B         LCD       356000
2             A      iphone       497000
3             A      iwatch       315000
4             B   Projector       413000
5             C   Hard disk        45000
6             B  Smartboard       211000
7             C   Pen drive        21000
Total expenditure category wise :
Item Category
A    1100000
B     980000
C      66000
Name: Expenditure, dtype: int64


Example 51: Consider the same dataframe QtrSales of the previous example and Group the row by the category, and print the average expenditure per category.

In [49]:
import pandas as pd  
QtrSales = pd.DataFrame({'Item Category':['A','B','A','A','B','C','B','C'],
                         'Item Name':['ipad','LCD','iphone','iwatch','Projector',
                                     'Hard disk','Smartboard','Pen drive'],
                         'Expenditure':[288000,356000,497000,315000,413000,45000,
                                       211000,21000]})  
print(QtrSales) 
print("Average expenditure category wise: ") 
print(QtrSales.groupby("Item Category")["Expenditure"].mean())

  Item Category   Item Name  Expenditure
0             A        ipad       288000
1             B         LCD       356000
2             A      iphone       497000
3             A      iwatch       315000
4             B   Projector       413000
5             C   Hard disk        45000
6             B  Smartboard       211000
7             C   Pen drive        21000
Average expenditure category wise: 
Item Category
A    366666.666667
B    326666.666667
C     33000.000000
Name: Expenditure, dtype: float64
